import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./UIComponent/Navbar/Navbar";
import Footer from "./UIComponent/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full overflow-hidden">
        <Navbar />
        <div className="overflow-auto inner_page">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
